export const LIMIT_POKEMONS = 6;

export const POKEMONS_REQUEST = {
    PENDING: 'POKEMONS_REQUEST_PENDING',
    SUCCESS: 'POKEMONS_REQUEST_SUCCESS',
    ERROR: 'POKEMONS_REQUEST_ERROR'
};

export const SET_FILTER = 'SET_FILTER';
export const SET_SEARCH_NAME = 'SET_SEARCH_NAME';
export const SEARCH_RESET = 'SEARCH_RESET';

export const SET_PAGE = {
    NEXT: 'SET_NEXT_PAGE',
    NUMBER: 'SET_PAGE_NUMBER',
    PREVIOUS: 'SET_PREVIOUS_PAGE'
};

export const SET_DISPLAYED_POKEMONS = 'SET_DISPLAYED_POKEMONS';

export const MOBILE_ACTIONS = {
    TOGGLE: 'TOGGLE_MOBILE_ACTIONS',
    CLOSE: 'CLOSE_MOBILE_ACTIONS'
};
